apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
spec:
  replicas: 3
  selector:
    app: web
  
  template:
    metadata:
      name: "rcpod"
      labels:
        app: web
    spec:
      containers:
      - name: "rccont"
        image: vimal13/apache-webserver-php