apiVersion: v1

kind: Pod
metadata:
  name: "db"
  labels:
    app: web

spec:
  containers:
  - name: "dbcon"
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "redhat"
    - name: MYSQL_DATABASE
      value: "wpdb"
    - name: MYSQL_USER
      value: "yash"
    - name: MYSQL_PASSWORD
      value: "redhat" 