apiVersion: v1

kind: Pod
metadata:
  name: "db"
  labels:
    app: web

spec:
  containers:
  - name: "dbcon"
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "YOURPASS"
    - name: MYSQL_DATABASE
      value: "YOURDB"
    - name: MYSQL_USER
      value: "YOURUSER"
    - name: MYSQL_PASSWORD
      value: "YOURPAAS" 