apiVersion: v1

kind: Pod
metadata:
  name: "db"
  labels:
    app: web

spec:
  containers:
  - name: "dbcon"
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secrets
          key: pass
    - name: MYSQL_DATABASE
      value: "YOURDB"
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: secrets
          key: user
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secrets
          key: pass 